name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          if [ -f 'yarn.lock' ]; then
            yarn install --immutable
          elif [ -f 'package-lock.json' ]; then
            npm ci
          elif [ -f 'pnpm-lock.yaml' ]; then
            pnpm install --frozen-lockfile
          else
            echo "No lockfile! Please commit your \`yarn.lock\`, \`package-lock.json\` or \`pnpm-lock.yaml\` files"
            exit 1
          fi
      - run: npm run lint .
